version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/railflow
      SPRING_DATASOURCE_USERNAME: railflow
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - postgres

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend


  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: railflow
      POSTGRES_USER: railflow
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
