spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/railflow
    username: railflow
    password: secret
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    hikari:
      initializationFailTimeout: 60000

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
