spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/railflow
    username: railflow
    password: secret
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    hikari:
      initializationFailTimeout: 60000

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: DEBUG                         # Все логи на уровне DEBUG
    org.springframework.web: DEBUG     # Логгировать все web-запросы
    yaroslav.khalin: DEBUG             # Твой пакет — логи твоих контроллеров, репозиториев и т.д.

server:
  port: 8080
  adress: 0.0.0.0
